"""restructure billing history for direct plan linkage

Revision ID: 1347f08b4908
Revises: 6c0e04dc7cba
Create Date: 2026-09-17 14:38:56.748368

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1347f08b4908'
down_revision: Union[str, Sequence[str], None] = '6c0e04dc7cba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_history', sa.Column('subscription_plan_id', sa.Integer(), nullable=False))
    op.add_column('billing_history', sa.Column('transaction_id', sa.String(length=50), nullable=False))
    op.add_column('billing_history', sa.Column('start_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('billing_history', sa.Column('end_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('billing_history', sa.Column('invoice_path', sa.String(length=500), nullable=True))
    op.drop_index(op.f('ix_billing_history_invoice_number'), table_name='billing_history')
    op.create_index(op.f('ix_billing_history_subscription_plan_id'), 'billing_history', ['subscription_plan_id'], unique=False)
    op.create_index(op.f('ix_billing_history_transaction_id'), 'billing_history', ['transaction_id'], unique=True)
    op.drop_constraint(op.f('billing_history_subscription_id_fkey'), 'billing_history', type_='foreignkey')
    op.create_foreign_key(
        op.f('billing_history_subscription_plan_id_fkey'),
        'billing_history', 'subscription_plans', ['subscription_plan_id'], ['id'], ondelete='RESTRICT',
    )
    op.drop_column('billing_history', 'period_start')
    op.drop_column('billing_history', 'subscription_id')
    op.drop_column('billing_history', 'invoice_number')
    op.drop_column('billing_history', 'period_end')
    op.drop_column('billing_history', 'plan_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_history', sa.Column('plan_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('billing_history', sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.add_column('billing_history', sa.Column('invoice_number', sa.VARCHAR(length=30), autoincrement=False, nullable=False))
    op.add_column('billing_history', sa.Column('subscription_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('billing_history', sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.drop_constraint(op.f('billing_history_subscription_plan_id_fkey'), 'billing_history', type_='foreignkey')
    op.create_foreign_key(op.f('billing_history_subscription_id_fkey'), 'billing_history', 'subscriptions', ['subscription_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_billing_history_transaction_id'), table_name='billing_history')
    op.drop_index(op.f('ix_billing_history_subscription_plan_id'), table_name='billing_history')
    op.create_index(op.f('ix_billing_history_invoice_number'), 'billing_history', ['invoice_number'], unique=True)
    op.drop_column('billing_history', 'invoice_path')
    op.drop_column('billing_history', 'end_date')
    op.drop_column('billing_history', 'start_date')
    op.drop_column('billing_history', 'transaction_id')
    op.drop_column('billing_history', 'subscription_plan_id')
    # ### end Alembic commands ###
