"""add configurable plan limits and seed basic premium pro

Revision ID: 6c0e04dc7cba
Revises: 7718fb0de206
Create Date: 2026-09-17 14:16:22.437779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c0e04dc7cba'
down_revision: Union[str, Sequence[str], None] = '7718fb0de206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


PLAN_NAMES = ["Basic", "Premium", "Pro"]

subscription_plans_table = sa.table(
    "subscription_plans",
    sa.column("name", sa.String),
    sa.column("slug", sa.String),
    sa.column("price", sa.Numeric),
    sa.column("billing_interval", sa.String),
    sa.column("max_posts", sa.Integer),
    sa.column("max_images", sa.Integer),
    sa.column("max_likes", sa.Integer),
    sa.column("max_comments", sa.Integer),
    sa.column("is_active", sa.Boolean),
)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('max_images', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('max_likes', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('max_comments', sa.Integer(), nullable=True))
    op.add_column('subscription_plans', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('subscription_plans_name_key'), 'subscription_plans', type_='unique')
    op.create_index(op.f('ix_subscription_plans_name'), 'subscription_plans', ['name'], unique=True)
    op.drop_column('subscription_plans', 'allow_image_upload')
    # ### end Alembic commands ###

    # Seed the three supported plans. NULL limits mean unlimited (Pro), the
    # same convention max_posts already used before this migration.
    op.bulk_insert(
        subscription_plans_table,
        [
            {
                "name": "Basic",
                "slug": "basic",
                "price": 4.99,
                "billing_interval": "month",
                "max_posts": 1,
                "max_images": 1,
                "max_likes": 5,
                "max_comments": 5,
                "is_active": True,
            },
            {
                "name": "Premium",
                "slug": "premium",
                "price": 9.99,
                "billing_interval": "month",
                "max_posts": 2,
                "max_images": 2,
                "max_likes": 25,
                "max_comments": 25,
                "is_active": True,
            },
            {
                "name": "Pro",
                "slug": "pro",
                "price": 19.99,
                "billing_interval": "month",
                "max_posts": None,
                "max_images": None,
                "max_likes": None,
                "max_comments": None,
                "is_active": True,
            },
        ],
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute(subscription_plans_table.delete().where(subscription_plans_table.c.name.in_(PLAN_NAMES)))

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_plans', sa.Column('allow_image_upload', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_subscription_plans_name'), table_name='subscription_plans')
    op.create_unique_constraint(op.f('subscription_plans_name_key'), 'subscription_plans', ['name'], postgresql_nulls_not_distinct=False)
    op.drop_column('subscription_plans', 'updated_at')
    op.drop_column('subscription_plans', 'max_comments')
    op.drop_column('subscription_plans', 'max_likes')
    op.drop_column('subscription_plans', 'max_images')
    # ### end Alembic commands ###
