"""add post_images gallery table

Revision ID: 94dcbecc071b
Revises: 3f0f35fc05d5
Create Date: 2026-09-17 15:40:20.580153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '94dcbecc071b'
down_revision: Union[str, Sequence[str], None] = '3f0f35fc05d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_images_id'), 'post_images', ['id'], unique=False)
    op.create_index(op.f('ix_post_images_post_id'), 'post_images', ['post_id'], unique=False)
    # ### end Alembic commands ###

    # Backfill: every existing post that already has an image gets a
    # matching post_images row, so the new per-post gallery count starts
    # consistent with what Post.image already showed -- an existing post
    # isn't treated as having zero images just because this table is new.
    op.execute(
        "INSERT INTO post_images (post_id, image) "
        "SELECT id, image FROM posts WHERE image IS NOT NULL"
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_images_post_id'), table_name='post_images')
    op.drop_index(op.f('ix_post_images_id'), table_name='post_images')
    op.drop_table('post_images')
    # ### end Alembic commands ###
